### ISSUE TITLE
config.yml can't deal with DEFAULTS section

### ISSUE THREAD

**Issue by jsgarvin** [jsgarvin/minionizer#2]
eg...

```
DEFAULTS: &DEFAULTS
  ssh:
    username: minionizer

my.server.com:
  <<: *DEFAULTS
  roles: [:bar, :baz]
```

Configuration.instance.minions returns...
    {"DEFAULTS"=>{"ssh"=>{"username"=>"minionizer"}}, "my.server.com"=>{"ssh"=>{"username"=>"minionizer"}, "roles"=>["bar", "baz"]}}

The defaults were successfully applied to the real server, but it shouldn't be loading "DEFAULTS" as a minion, too.  Can probably just get stripped off when the config loads.
